// Auto-generated Dataset for MastiGuardAI Telemetry & Herd Analytics
const HERD_DATASET = [
  {
    "Animal_ID": "IN-DAIRY-1000",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 116,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.547,
    "Milk_pH": 6.888,
    "Milk_Temperature_C": 39.66,
    "Milk_Yield_Liters": 11.27,
    "Somatic_Cell_Count_Actual": 812288,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1001",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 4,
    "Days_In_Milk": 192,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.862,
    "Milk_pH": 6.631,
    "Milk_Temperature_C": 38.51,
    "Milk_Yield_Liters": 18.38,
    "Somatic_Cell_Count_Actual": 82655,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1002",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 4,
    "Parity": 4,
    "Days_In_Milk": 188,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.85,
    "Milk_pH": 6.617,
    "Milk_Temperature_C": 38.71,
    "Milk_Yield_Liters": 13.88,
    "Somatic_Cell_Count_Actual": 43111,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1003",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 2,
    "Days_In_Milk": 117,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.011,
    "Milk_pH": 6.654,
    "Milk_Temperature_C": 38.99,
    "Milk_Yield_Liters": 15.66,
    "Somatic_Cell_Count_Actual": 54053,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1004",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 3,
    "Parity": 3,
    "Days_In_Milk": 210,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.54,
    "Milk_pH": 7.191,
    "Milk_Temperature_C": 40.57,
    "Milk_Yield_Liters": 5.93,
    "Somatic_Cell_Count_Actual": 2174008,
    "Risk_Tier_Label": "High Risk",
    "Risk_Tier_Code": 3
  },
  {
    "Animal_ID": "IN-DAIRY-1005",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 7,
    "Parity": 1,
    "Days_In_Milk": 64,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.92,
    "Milk_pH": 6.73,
    "Milk_Temperature_C": 38.44,
    "Milk_Yield_Liters": 9.38,
    "Somatic_Cell_Count_Actual": 98787,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1006",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 3,
    "Parity": 3,
    "Days_In_Milk": 193,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.83,
    "Milk_pH": 6.58,
    "Milk_Temperature_C": 39.04,
    "Milk_Yield_Liters": 11.22,
    "Somatic_Cell_Count_Actual": 44928,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1007",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 9,
    "Parity": 1,
    "Days_In_Milk": 160,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.855,
    "Milk_pH": 6.603,
    "Milk_Temperature_C": 38.77,
    "Milk_Yield_Liters": 10.52,
    "Somatic_Cell_Count_Actual": 49196,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1008",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 101,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.136,
    "Milk_pH": 6.717,
    "Milk_Temperature_C": 38.69,
    "Milk_Yield_Liters": 12.24,
    "Somatic_Cell_Count_Actual": 285932,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1009",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 5,
    "Parity": 1,
    "Days_In_Milk": 233,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.649,
    "Milk_pH": 6.632,
    "Milk_Temperature_C": 38.74,
    "Milk_Yield_Liters": 8.93,
    "Somatic_Cell_Count_Actual": 53517,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1010",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 3,
    "Parity": 2,
    "Days_In_Milk": 248,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.989,
    "Milk_pH": 6.651,
    "Milk_Temperature_C": 38.37,
    "Milk_Yield_Liters": 12.39,
    "Somatic_Cell_Count_Actual": 55911,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1011",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 3,
    "Parity": 5,
    "Days_In_Milk": 130,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.815,
    "Milk_pH": 6.681,
    "Milk_Temperature_C": 38.79,
    "Milk_Yield_Liters": 14.54,
    "Somatic_Cell_Count_Actual": 48187,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1012",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 7,
    "Parity": 2,
    "Days_In_Milk": 175,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 5.047,
    "Milk_pH": 6.543,
    "Milk_Temperature_C": 38.59,
    "Milk_Yield_Liters": 11.41,
    "Somatic_Cell_Count_Actual": 65464,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1013",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 111,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.809,
    "Milk_pH": 6.644,
    "Milk_Temperature_C": 38.42,
    "Milk_Yield_Liters": 10.55,
    "Somatic_Cell_Count_Actual": 39591,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1014",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 2,
    "Days_In_Milk": 224,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.857,
    "Milk_pH": 6.684,
    "Milk_Temperature_C": 38.69,
    "Milk_Yield_Liters": 12.56,
    "Somatic_Cell_Count_Actual": 47345,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1015",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 4,
    "Days_In_Milk": 217,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.856,
    "Milk_pH": 6.565,
    "Milk_Temperature_C": 38.96,
    "Milk_Yield_Liters": 13.92,
    "Somatic_Cell_Count_Actual": 43807,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1016",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 5,
    "Days_In_Milk": 176,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.94,
    "Milk_pH": 6.569,
    "Milk_Temperature_C": 38.57,
    "Milk_Yield_Liters": 11.16,
    "Somatic_Cell_Count_Actual": 51586,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1017",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 4,
    "Days_In_Milk": 194,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.643,
    "Milk_pH": 6.572,
    "Milk_Temperature_C": 38.09,
    "Milk_Yield_Liters": 14.49,
    "Somatic_Cell_Count_Actual": 799277,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1018",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 6,
    "Parity": 2,
    "Days_In_Milk": 92,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.872,
    "Milk_pH": 6.73,
    "Milk_Temperature_C": 38.86,
    "Milk_Yield_Liters": 9.64,
    "Somatic_Cell_Count_Actual": 535697,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1019",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 240,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.81,
    "Milk_pH": 6.621,
    "Milk_Temperature_C": 39.11,
    "Milk_Yield_Liters": 10.55,
    "Somatic_Cell_Count_Actual": 69380,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1020",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 7,
    "Parity": 5,
    "Days_In_Milk": 102,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.583,
    "Milk_pH": 7.17,
    "Milk_Temperature_C": 40.95,
    "Milk_Yield_Liters": 15.52,
    "Somatic_Cell_Count_Actual": 2728024,
    "Risk_Tier_Label": "High Risk",
    "Risk_Tier_Code": 3
  },
  {
    "Animal_ID": "IN-DAIRY-1021",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 210,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.893,
    "Milk_pH": 6.627,
    "Milk_Temperature_C": 38.69,
    "Milk_Yield_Liters": 14.78,
    "Somatic_Cell_Count_Actual": 65215,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1022",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 129,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.912,
    "Milk_pH": 6.69,
    "Milk_Temperature_C": 38.53,
    "Milk_Yield_Liters": 11.88,
    "Somatic_Cell_Count_Actual": 53419,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1023",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 6,
    "Parity": 3,
    "Days_In_Milk": 224,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.176,
    "Milk_pH": 6.8,
    "Milk_Temperature_C": 38.67,
    "Milk_Yield_Liters": 12.15,
    "Somatic_Cell_Count_Actual": 193450,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1024",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 1,
    "Days_In_Milk": 208,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.076,
    "Milk_pH": 6.804,
    "Milk_Temperature_C": 38.8,
    "Milk_Yield_Liters": 18.2,
    "Somatic_Cell_Count_Actual": 320605,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1025",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 5,
    "Parity": 4,
    "Days_In_Milk": 147,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.9,
    "Milk_pH": 6.581,
    "Milk_Temperature_C": 38.84,
    "Milk_Yield_Liters": 12.39,
    "Somatic_Cell_Count_Actual": 75996,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1026",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 4,
    "Parity": 4,
    "Days_In_Milk": 104,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.888,
    "Milk_pH": 6.633,
    "Milk_Temperature_C": 38.53,
    "Milk_Yield_Liters": 16.74,
    "Somatic_Cell_Count_Actual": 78490,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1027",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 6,
    "Parity": 3,
    "Days_In_Milk": 68,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.781,
    "Milk_pH": 6.604,
    "Milk_Temperature_C": 39.01,
    "Milk_Yield_Liters": 14.76,
    "Somatic_Cell_Count_Actual": 54405,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1028",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 4,
    "Parity": 3,
    "Days_In_Milk": 189,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.876,
    "Milk_pH": 6.565,
    "Milk_Temperature_C": 38.69,
    "Milk_Yield_Liters": 13.13,
    "Somatic_Cell_Count_Actual": 75135,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1029",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 3,
    "Days_In_Milk": 92,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.661,
    "Milk_pH": 6.581,
    "Milk_Temperature_C": 38.92,
    "Milk_Yield_Liters": 12.49,
    "Somatic_Cell_Count_Actual": 33252,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1030",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 2,
    "Days_In_Milk": 200,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.875,
    "Milk_pH": 6.538,
    "Milk_Temperature_C": 38.62,
    "Milk_Yield_Liters": 16.11,
    "Somatic_Cell_Count_Actual": 89659,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1031",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 3,
    "Parity": 5,
    "Days_In_Milk": 236,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.701,
    "Milk_pH": 6.655,
    "Milk_Temperature_C": 38.92,
    "Milk_Yield_Liters": 11.82,
    "Somatic_Cell_Count_Actual": 106589,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1032",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 2,
    "Days_In_Milk": 200,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.798,
    "Milk_pH": 6.534,
    "Milk_Temperature_C": 38.41,
    "Milk_Yield_Liters": 15.2,
    "Somatic_Cell_Count_Actual": 47820,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1033",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 175,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.889,
    "Milk_pH": 6.681,
    "Milk_Temperature_C": 38.93,
    "Milk_Yield_Liters": 8.64,
    "Somatic_Cell_Count_Actual": 52909,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1034",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 182,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.894,
    "Milk_pH": 6.565,
    "Milk_Temperature_C": 38.89,
    "Milk_Yield_Liters": 16.79,
    "Somatic_Cell_Count_Actual": 57014,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1035",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 7,
    "Parity": 1,
    "Days_In_Milk": 244,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.884,
    "Milk_pH": 6.628,
    "Milk_Temperature_C": 38.77,
    "Milk_Yield_Liters": 8.12,
    "Somatic_Cell_Count_Actual": 50387,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1036",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 6,
    "Parity": 1,
    "Days_In_Milk": 114,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.95,
    "Milk_pH": 6.679,
    "Milk_Temperature_C": 38.64,
    "Milk_Yield_Liters": 13.78,
    "Somatic_Cell_Count_Actual": 63768,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1037",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 8,
    "Parity": 5,
    "Days_In_Milk": 134,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.764,
    "Milk_pH": 6.532,
    "Milk_Temperature_C": 38.73,
    "Milk_Yield_Liters": 9.67,
    "Somatic_Cell_Count_Actual": 76306,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1038",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 3,
    "Days_In_Milk": 233,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.277,
    "Milk_pH": 6.774,
    "Milk_Temperature_C": 38.82,
    "Milk_Yield_Liters": 13.28,
    "Somatic_Cell_Count_Actual": 205384,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1039",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 180,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.751,
    "Milk_pH": 6.497,
    "Milk_Temperature_C": 38.48,
    "Milk_Yield_Liters": 12.93,
    "Somatic_Cell_Count_Actual": 48914,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1040",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 3,
    "Days_In_Milk": 116,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.766,
    "Milk_pH": 6.572,
    "Milk_Temperature_C": 38.58,
    "Milk_Yield_Liters": 11.06,
    "Somatic_Cell_Count_Actual": 57376,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1041",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 3,
    "Parity": 1,
    "Days_In_Milk": 100,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.042,
    "Milk_pH": 6.617,
    "Milk_Temperature_C": 38.71,
    "Milk_Yield_Liters": 14.91,
    "Somatic_Cell_Count_Actual": 54150,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1042",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 110,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.051,
    "Milk_pH": 6.624,
    "Milk_Temperature_C": 38.57,
    "Milk_Yield_Liters": 12.65,
    "Somatic_Cell_Count_Actual": 85884,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1043",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 4,
    "Days_In_Milk": 166,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.872,
    "Milk_pH": 6.721,
    "Milk_Temperature_C": 37.97,
    "Milk_Yield_Liters": 20.09,
    "Somatic_Cell_Count_Actual": 63442,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1044",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 5,
    "Parity": 2,
    "Days_In_Milk": 53,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.366,
    "Milk_pH": 7.061,
    "Milk_Temperature_C": 39.4,
    "Milk_Yield_Liters": 9.81,
    "Somatic_Cell_Count_Actual": 519847,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1045",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 185,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.247,
    "Milk_pH": 6.669,
    "Milk_Temperature_C": 38.61,
    "Milk_Yield_Liters": 12.24,
    "Somatic_Cell_Count_Actual": 303701,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1046",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 5,
    "Parity": 3,
    "Days_In_Milk": 178,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.069,
    "Milk_pH": 6.821,
    "Milk_Temperature_C": 39.89,
    "Milk_Yield_Liters": 7.8,
    "Somatic_Cell_Count_Actual": 414950,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1047",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 5,
    "Days_In_Milk": 181,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 5.421,
    "Milk_pH": 6.864,
    "Milk_Temperature_C": 39.78,
    "Milk_Yield_Liters": 16.73,
    "Somatic_Cell_Count_Actual": 910397,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1048",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 7,
    "Parity": 1,
    "Days_In_Milk": 177,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.848,
    "Milk_pH": 6.514,
    "Milk_Temperature_C": 38.47,
    "Milk_Yield_Liters": 10.85,
    "Somatic_Cell_Count_Actual": 69373,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1049",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 5,
    "Days_In_Milk": 47,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.896,
    "Milk_pH": 6.616,
    "Milk_Temperature_C": 38.35,
    "Milk_Yield_Liters": 20.89,
    "Somatic_Cell_Count_Actual": 65295,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1050",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 248,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.774,
    "Milk_pH": 6.686,
    "Milk_Temperature_C": 38.8,
    "Milk_Yield_Liters": 15.37,
    "Somatic_Cell_Count_Actual": 69521,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1051",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 3,
    "Parity": 5,
    "Days_In_Milk": 64,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.797,
    "Milk_pH": 6.585,
    "Milk_Temperature_C": 38.57,
    "Milk_Yield_Liters": 13.15,
    "Somatic_Cell_Count_Actual": 52719,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1052",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 132,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.932,
    "Milk_pH": 6.591,
    "Milk_Temperature_C": 38.59,
    "Milk_Yield_Liters": 14.35,
    "Somatic_Cell_Count_Actual": 48648,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1053",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 1,
    "Days_In_Milk": 226,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.939,
    "Milk_pH": 6.544,
    "Milk_Temperature_C": 38.66,
    "Milk_Yield_Liters": 10.68,
    "Somatic_Cell_Count_Actual": 49458,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1054",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 5,
    "Days_In_Milk": 202,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.133,
    "Milk_pH": 6.701,
    "Milk_Temperature_C": 38.35,
    "Milk_Yield_Liters": 18.82,
    "Somatic_Cell_Count_Actual": 270447,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1055",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 5,
    "Parity": 4,
    "Days_In_Milk": 224,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.89,
    "Milk_pH": 6.636,
    "Milk_Temperature_C": 38.53,
    "Milk_Yield_Liters": 11.36,
    "Somatic_Cell_Count_Actual": 71757,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1056",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 156,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 5.13,
    "Milk_pH": 6.661,
    "Milk_Temperature_C": 38.82,
    "Milk_Yield_Liters": 17.54,
    "Somatic_Cell_Count_Actual": 272071,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1057",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 220,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.05,
    "Milk_pH": 6.58,
    "Milk_Temperature_C": 38.22,
    "Milk_Yield_Liters": 5.7,
    "Somatic_Cell_Count_Actual": 70077,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1058",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 163,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.531,
    "Milk_pH": 7.209,
    "Milk_Temperature_C": 40.31,
    "Milk_Yield_Liters": 8.63,
    "Somatic_Cell_Count_Actual": 2077488,
    "Risk_Tier_Label": "High Risk",
    "Risk_Tier_Code": 3
  },
  {
    "Animal_ID": "IN-DAIRY-1059",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 3,
    "Days_In_Milk": 106,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.028,
    "Milk_pH": 6.544,
    "Milk_Temperature_C": 38.69,
    "Milk_Yield_Liters": 10.27,
    "Somatic_Cell_Count_Actual": 53864,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1060",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 4,
    "Parity": 4,
    "Days_In_Milk": 212,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.714,
    "Milk_pH": 6.629,
    "Milk_Temperature_C": 38.51,
    "Milk_Yield_Liters": 12.43,
    "Somatic_Cell_Count_Actual": 48411,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1061",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 4,
    "Parity": 3,
    "Days_In_Milk": 247,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.809,
    "Milk_pH": 6.641,
    "Milk_Temperature_C": 38.91,
    "Milk_Yield_Liters": 9.52,
    "Somatic_Cell_Count_Actual": 80565,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1062",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 9,
    "Parity": 4,
    "Days_In_Milk": 97,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.985,
    "Milk_pH": 6.644,
    "Milk_Temperature_C": 38.73,
    "Milk_Yield_Liters": 13.96,
    "Somatic_Cell_Count_Actual": 73172,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1063",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 4,
    "Parity": 1,
    "Days_In_Milk": 59,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.804,
    "Milk_pH": 6.625,
    "Milk_Temperature_C": 38.66,
    "Milk_Yield_Liters": 4.81,
    "Somatic_Cell_Count_Actual": 91680,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1064",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 89,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.81,
    "Milk_pH": 6.633,
    "Milk_Temperature_C": 38.83,
    "Milk_Yield_Liters": 13.36,
    "Somatic_Cell_Count_Actual": 763266,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1065",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 8,
    "Parity": 5,
    "Days_In_Milk": 65,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 4.818,
    "Milk_pH": 6.522,
    "Milk_Temperature_C": 38.92,
    "Milk_Yield_Liters": 16.37,
    "Somatic_Cell_Count_Actual": 58364,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1066",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 1,
    "Days_In_Milk": 186,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.817,
    "Milk_pH": 6.643,
    "Milk_Temperature_C": 38.63,
    "Milk_Yield_Liters": 13.02,
    "Somatic_Cell_Count_Actual": 62693,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1067",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 6,
    "Parity": 4,
    "Days_In_Milk": 139,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.165,
    "Milk_pH": 6.964,
    "Milk_Temperature_C": 39.79,
    "Milk_Yield_Liters": 12.51,
    "Somatic_Cell_Count_Actual": 718945,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1068",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 126,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.689,
    "Milk_pH": 6.645,
    "Milk_Temperature_C": 38.8,
    "Milk_Yield_Liters": 18.05,
    "Somatic_Cell_Count_Actual": 48898,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1069",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 121,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.893,
    "Milk_pH": 6.629,
    "Milk_Temperature_C": 38.67,
    "Milk_Yield_Liters": 15.94,
    "Somatic_Cell_Count_Actual": 56753,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1070",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 1,
    "Days_In_Milk": 52,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.783,
    "Milk_pH": 6.521,
    "Milk_Temperature_C": 38.64,
    "Milk_Yield_Liters": 13.86,
    "Somatic_Cell_Count_Actual": 88993,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1071",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 3,
    "Days_In_Milk": 103,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.462,
    "Milk_pH": 7.219,
    "Milk_Temperature_C": 40.57,
    "Milk_Yield_Liters": 10.31,
    "Somatic_Cell_Count_Actual": 3379399,
    "Risk_Tier_Label": "High Risk",
    "Risk_Tier_Code": 3
  },
  {
    "Animal_ID": "IN-DAIRY-1072",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 77,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.872,
    "Milk_pH": 6.633,
    "Milk_Temperature_C": 38.43,
    "Milk_Yield_Liters": 16.81,
    "Somatic_Cell_Count_Actual": 53611,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1073",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 4,
    "Parity": 3,
    "Days_In_Milk": 234,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.798,
    "Milk_pH": 6.658,
    "Milk_Temperature_C": 38.48,
    "Milk_Yield_Liters": 8.88,
    "Somatic_Cell_Count_Actual": 30713,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1074",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 2,
    "Days_In_Milk": 163,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.824,
    "Milk_pH": 6.629,
    "Milk_Temperature_C": 38.87,
    "Milk_Yield_Liters": 12.53,
    "Somatic_Cell_Count_Actual": 61404,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1075",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 6,
    "Parity": 3,
    "Days_In_Milk": 235,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.907,
    "Milk_pH": 6.667,
    "Milk_Temperature_C": 38.06,
    "Milk_Yield_Liters": 11.94,
    "Somatic_Cell_Count_Actual": 70006,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1076",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 4,
    "Days_In_Milk": 151,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.374,
    "Milk_pH": 6.635,
    "Milk_Temperature_C": 39.02,
    "Milk_Yield_Liters": 8.87,
    "Somatic_Cell_Count_Actual": 224954,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1077",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 1,
    "Days_In_Milk": 155,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 4.809,
    "Milk_pH": 6.62,
    "Milk_Temperature_C": 38.5,
    "Milk_Yield_Liters": 10.57,
    "Somatic_Cell_Count_Actual": 58140,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1078",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 160,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.83,
    "Milk_pH": 6.509,
    "Milk_Temperature_C": 38.37,
    "Milk_Yield_Liters": 18.31,
    "Somatic_Cell_Count_Actual": 62019,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1079",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 1,
    "Days_In_Milk": 157,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.914,
    "Milk_pH": 6.589,
    "Milk_Temperature_C": 38.56,
    "Milk_Yield_Liters": 12.67,
    "Somatic_Cell_Count_Actual": 46159,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1080",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 4,
    "Days_In_Milk": 99,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.126,
    "Milk_pH": 6.662,
    "Milk_Temperature_C": 38.87,
    "Milk_Yield_Liters": 18.9,
    "Somatic_Cell_Count_Actual": 199936,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1081",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 2,
    "Days_In_Milk": 143,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.88,
    "Milk_pH": 6.563,
    "Milk_Temperature_C": 38.65,
    "Milk_Yield_Liters": 13.42,
    "Somatic_Cell_Count_Actual": 53169,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1082",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 2,
    "Days_In_Milk": 87,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5,
    "Milk_pH": 6.577,
    "Milk_Temperature_C": 38.66,
    "Milk_Yield_Liters": 19.19,
    "Somatic_Cell_Count_Actual": 77432,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1083",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 5,
    "Parity": 5,
    "Days_In_Milk": 86,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.034,
    "Milk_pH": 6.623,
    "Milk_Temperature_C": 38.77,
    "Milk_Yield_Liters": 11.88,
    "Somatic_Cell_Count_Actual": 52184,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1084",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 54,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.751,
    "Milk_pH": 6.677,
    "Milk_Temperature_C": 38.43,
    "Milk_Yield_Liters": 11.54,
    "Somatic_Cell_Count_Actual": 52992,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1085",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 103,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.936,
    "Milk_pH": 6.619,
    "Milk_Temperature_C": 38.06,
    "Milk_Yield_Liters": 10.73,
    "Somatic_Cell_Count_Actual": 65822,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1086",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 5,
    "Days_In_Milk": 63,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.997,
    "Milk_pH": 6.69,
    "Milk_Temperature_C": 38.52,
    "Milk_Yield_Liters": 10.89,
    "Somatic_Cell_Count_Actual": 77317,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1087",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 220,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.953,
    "Milk_pH": 6.732,
    "Milk_Temperature_C": 38.96,
    "Milk_Yield_Liters": 11.81,
    "Somatic_Cell_Count_Actual": 58561,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1088",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 3,
    "Days_In_Milk": 52,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.856,
    "Milk_pH": 6.586,
    "Milk_Temperature_C": 38.87,
    "Milk_Yield_Liters": 13.6,
    "Somatic_Cell_Count_Actual": 78915,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1089",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 6,
    "Parity": 5,
    "Days_In_Milk": 66,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.681,
    "Milk_pH": 6.679,
    "Milk_Temperature_C": 38.34,
    "Milk_Yield_Liters": 10.81,
    "Somatic_Cell_Count_Actual": 69098,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1090",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 5,
    "Days_In_Milk": 76,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.658,
    "Milk_pH": 6.618,
    "Milk_Temperature_C": 38.64,
    "Milk_Yield_Liters": 16.44,
    "Somatic_Cell_Count_Actual": 54359,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1091",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 2,
    "Days_In_Milk": 64,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.861,
    "Milk_pH": 6.616,
    "Milk_Temperature_C": 38.72,
    "Milk_Yield_Liters": 10.59,
    "Somatic_Cell_Count_Actual": 74047,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1092",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 4,
    "Days_In_Milk": 173,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.832,
    "Milk_pH": 6.582,
    "Milk_Temperature_C": 38.35,
    "Milk_Yield_Liters": 21.56,
    "Somatic_Cell_Count_Actual": 54098,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1093",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 7,
    "Parity": 5,
    "Days_In_Milk": 62,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.704,
    "Milk_pH": 6.577,
    "Milk_Temperature_C": 38.44,
    "Milk_Yield_Liters": 15.63,
    "Somatic_Cell_Count_Actual": 48651,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1094",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 4,
    "Days_In_Milk": 206,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.85,
    "Milk_pH": 6.577,
    "Milk_Temperature_C": 38.9,
    "Milk_Yield_Liters": 13.18,
    "Somatic_Cell_Count_Actual": 55105,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1095",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 6,
    "Parity": 2,
    "Days_In_Milk": 132,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.869,
    "Milk_pH": 6.543,
    "Milk_Temperature_C": 38.59,
    "Milk_Yield_Liters": 9.94,
    "Somatic_Cell_Count_Actual": 40003,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1096",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 3,
    "Parity": 1,
    "Days_In_Milk": 232,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.235,
    "Milk_pH": 6.901,
    "Milk_Temperature_C": 39.43,
    "Milk_Yield_Liters": 7.47,
    "Somatic_Cell_Count_Actual": 616629,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1097",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 46,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.784,
    "Milk_pH": 6.606,
    "Milk_Temperature_C": 39.05,
    "Milk_Yield_Liters": 19.39,
    "Somatic_Cell_Count_Actual": 85177,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1098",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 163,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.839,
    "Milk_pH": 6.594,
    "Milk_Temperature_C": 38.5,
    "Milk_Yield_Liters": 11.71,
    "Somatic_Cell_Count_Actual": 43823,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1099",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 5,
    "Parity": 5,
    "Days_In_Milk": 70,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.507,
    "Milk_pH": 7.136,
    "Milk_Temperature_C": 40.63,
    "Milk_Yield_Liters": 13.2,
    "Somatic_Cell_Count_Actual": 2106145,
    "Risk_Tier_Label": "High Risk",
    "Risk_Tier_Code": 3
  },
  {
    "Animal_ID": "IN-DAIRY-1100",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 194,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.658,
    "Milk_pH": 6.643,
    "Milk_Temperature_C": 38.99,
    "Milk_Yield_Liters": 9.68,
    "Somatic_Cell_Count_Actual": 52473,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1101",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 4,
    "Days_In_Milk": 247,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.774,
    "Milk_pH": 6.577,
    "Milk_Temperature_C": 38.55,
    "Milk_Yield_Liters": 12.69,
    "Somatic_Cell_Count_Actual": 504088,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1102",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 183,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.775,
    "Milk_pH": 6.69,
    "Milk_Temperature_C": 38.88,
    "Milk_Yield_Liters": 15.15,
    "Somatic_Cell_Count_Actual": 49635,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1103",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 2,
    "Days_In_Milk": 213,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.718,
    "Milk_pH": 6.591,
    "Milk_Temperature_C": 38.79,
    "Milk_Yield_Liters": 20.05,
    "Somatic_Cell_Count_Actual": 58598,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1104",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 4,
    "Parity": 3,
    "Days_In_Milk": 154,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.706,
    "Milk_pH": 6.653,
    "Milk_Temperature_C": 38.74,
    "Milk_Yield_Liters": 9.65,
    "Somatic_Cell_Count_Actual": 514002,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1105",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 1,
    "Days_In_Milk": 197,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.223,
    "Milk_pH": 6.911,
    "Milk_Temperature_C": 39.42,
    "Milk_Yield_Liters": 7.57,
    "Somatic_Cell_Count_Actual": 933697,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1106",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 1,
    "Days_In_Milk": 192,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.848,
    "Milk_pH": 6.632,
    "Milk_Temperature_C": 38.7,
    "Milk_Yield_Liters": 12.21,
    "Somatic_Cell_Count_Actual": 45241,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1107",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 3,
    "Days_In_Milk": 119,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 4.999,
    "Milk_pH": 6.692,
    "Milk_Temperature_C": 38.19,
    "Milk_Yield_Liters": 15.16,
    "Somatic_Cell_Count_Actual": 63609,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1108",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 2,
    "Days_In_Milk": 114,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.85,
    "Milk_pH": 6.693,
    "Milk_Temperature_C": 38.43,
    "Milk_Yield_Liters": 17.56,
    "Somatic_Cell_Count_Actual": 69051,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1109",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 9,
    "Parity": 2,
    "Days_In_Milk": 221,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.949,
    "Milk_pH": 6.664,
    "Milk_Temperature_C": 38.51,
    "Milk_Yield_Liters": 10.07,
    "Somatic_Cell_Count_Actual": 46501,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1110",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 5,
    "Days_In_Milk": 224,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.802,
    "Milk_pH": 7.332,
    "Milk_Temperature_C": 40.12,
    "Milk_Yield_Liters": 10.18,
    "Somatic_Cell_Count_Actual": 2276099,
    "Risk_Tier_Label": "High Risk",
    "Risk_Tier_Code": 3
  },
  {
    "Animal_ID": "IN-DAIRY-1111",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 137,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.104,
    "Milk_pH": 6.724,
    "Milk_Temperature_C": 38.87,
    "Milk_Yield_Liters": 10.13,
    "Somatic_Cell_Count_Actual": 296038,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1112",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 1,
    "Days_In_Milk": 230,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.942,
    "Milk_pH": 6.606,
    "Milk_Temperature_C": 38.41,
    "Milk_Yield_Liters": 16.25,
    "Somatic_Cell_Count_Actual": 84285,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1113",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 128,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.953,
    "Milk_pH": 6.559,
    "Milk_Temperature_C": 38.3,
    "Milk_Yield_Liters": 9.4,
    "Somatic_Cell_Count_Actual": 46521,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1114",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 5,
    "Parity": 5,
    "Days_In_Milk": 214,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.931,
    "Milk_pH": 6.618,
    "Milk_Temperature_C": 38.78,
    "Milk_Yield_Liters": 12.49,
    "Somatic_Cell_Count_Actual": 69134,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1115",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 3,
    "Parity": 5,
    "Days_In_Milk": 82,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.945,
    "Milk_pH": 6.665,
    "Milk_Temperature_C": 38.5,
    "Milk_Yield_Liters": 12.54,
    "Somatic_Cell_Count_Actual": 47456,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1116",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 9,
    "Parity": 1,
    "Days_In_Milk": 187,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 5.364,
    "Milk_pH": 7.036,
    "Milk_Temperature_C": 39.98,
    "Milk_Yield_Liters": 8.62,
    "Somatic_Cell_Count_Actual": 779329,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1117",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 8,
    "Parity": 2,
    "Days_In_Milk": 116,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.66,
    "Milk_pH": 6.681,
    "Milk_Temperature_C": 38.59,
    "Milk_Yield_Liters": 6.83,
    "Somatic_Cell_Count_Actual": 57913,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1118",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 5,
    "Days_In_Milk": 197,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.852,
    "Milk_pH": 6.499,
    "Milk_Temperature_C": 38.44,
    "Milk_Yield_Liters": 20.08,
    "Somatic_Cell_Count_Actual": 76642,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1119",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 1,
    "Days_In_Milk": 104,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.139,
    "Milk_pH": 6.711,
    "Milk_Temperature_C": 38.52,
    "Milk_Yield_Liters": 16.59,
    "Somatic_Cell_Count_Actual": 283823,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1120",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 2,
    "Days_In_Milk": 124,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.871,
    "Milk_pH": 6.622,
    "Milk_Temperature_C": 38.78,
    "Milk_Yield_Liters": 12.73,
    "Somatic_Cell_Count_Actual": 50614,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1121",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 246,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.967,
    "Milk_pH": 6.662,
    "Milk_Temperature_C": 38.74,
    "Milk_Yield_Liters": 9.99,
    "Somatic_Cell_Count_Actual": 66420,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1122",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 6,
    "Parity": 2,
    "Days_In_Milk": 203,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.87,
    "Milk_pH": 6.621,
    "Milk_Temperature_C": 38.88,
    "Milk_Yield_Liters": 6.59,
    "Somatic_Cell_Count_Actual": 47715,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1123",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 2,
    "Days_In_Milk": 107,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.896,
    "Milk_pH": 6.552,
    "Milk_Temperature_C": 38.26,
    "Milk_Yield_Liters": 7.22,
    "Somatic_Cell_Count_Actual": 44913,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1124",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 1,
    "Days_In_Milk": 130,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.921,
    "Milk_pH": 6.642,
    "Milk_Temperature_C": 38.53,
    "Milk_Yield_Liters": 16.31,
    "Somatic_Cell_Count_Actual": 48231,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1125",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 2,
    "Days_In_Milk": 98,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.897,
    "Milk_pH": 6.639,
    "Milk_Temperature_C": 38.4,
    "Milk_Yield_Liters": 15.64,
    "Somatic_Cell_Count_Actual": 41155,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1126",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 3,
    "Parity": 2,
    "Days_In_Milk": 192,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.879,
    "Milk_pH": 6.552,
    "Milk_Temperature_C": 38.53,
    "Milk_Yield_Liters": 9.47,
    "Somatic_Cell_Count_Actual": 46613,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1127",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 7,
    "Parity": 2,
    "Days_In_Milk": 219,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.121,
    "Milk_pH": 6.766,
    "Milk_Temperature_C": 39.34,
    "Milk_Yield_Liters": 11.43,
    "Somatic_Cell_Count_Actual": 240371,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1128",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 4,
    "Parity": 3,
    "Days_In_Milk": 219,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 4.846,
    "Milk_pH": 6.689,
    "Milk_Temperature_C": 38.72,
    "Milk_Yield_Liters": 7.7,
    "Somatic_Cell_Count_Actual": 72165,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1129",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 189,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.003,
    "Milk_pH": 6.61,
    "Milk_Temperature_C": 38.8,
    "Milk_Yield_Liters": 10.01,
    "Somatic_Cell_Count_Actual": 89513,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1130",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 140,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.855,
    "Milk_pH": 6.642,
    "Milk_Temperature_C": 38.35,
    "Milk_Yield_Liters": 8.92,
    "Somatic_Cell_Count_Actual": 72013,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1131",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 4,
    "Days_In_Milk": 73,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.967,
    "Milk_pH": 6.636,
    "Milk_Temperature_C": 37.95,
    "Milk_Yield_Liters": 17.25,
    "Somatic_Cell_Count_Actual": 56908,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1132",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 5,
    "Parity": 5,
    "Days_In_Milk": 122,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 4.882,
    "Milk_pH": 6.619,
    "Milk_Temperature_C": 38.54,
    "Milk_Yield_Liters": 10.58,
    "Somatic_Cell_Count_Actual": 40386,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1133",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 9,
    "Parity": 2,
    "Days_In_Milk": 84,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.857,
    "Milk_pH": 6.575,
    "Milk_Temperature_C": 38.52,
    "Milk_Yield_Liters": 10.41,
    "Somatic_Cell_Count_Actual": 78519,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1134",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 8,
    "Parity": 2,
    "Days_In_Milk": 48,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.901,
    "Milk_pH": 6.605,
    "Milk_Temperature_C": 38.77,
    "Milk_Yield_Liters": 7.83,
    "Somatic_Cell_Count_Actual": 673506,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1135",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 6,
    "Parity": 4,
    "Days_In_Milk": 77,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.02,
    "Milk_pH": 6.622,
    "Milk_Temperature_C": 38.31,
    "Milk_Yield_Liters": 10.74,
    "Somatic_Cell_Count_Actual": 617923,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1136",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 9,
    "Parity": 3,
    "Days_In_Milk": 119,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 5.341,
    "Milk_pH": 6.829,
    "Milk_Temperature_C": 39.81,
    "Milk_Yield_Liters": 9.33,
    "Somatic_Cell_Count_Actual": 420115,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1137",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 2,
    "Days_In_Milk": 168,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.835,
    "Milk_pH": 6.589,
    "Milk_Temperature_C": 38.64,
    "Milk_Yield_Liters": 10.57,
    "Somatic_Cell_Count_Actual": 86688,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1138",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 7,
    "Parity": 5,
    "Days_In_Milk": 205,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.716,
    "Milk_pH": 6.665,
    "Milk_Temperature_C": 38.49,
    "Milk_Yield_Liters": 8.69,
    "Somatic_Cell_Count_Actual": 74623,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1139",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 2,
    "Days_In_Milk": 228,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.92,
    "Milk_pH": 6.579,
    "Milk_Temperature_C": 38.69,
    "Milk_Yield_Liters": 15.8,
    "Somatic_Cell_Count_Actual": 69567,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1140",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 5,
    "Days_In_Milk": 167,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.014,
    "Milk_pH": 6.68,
    "Milk_Temperature_C": 38.57,
    "Milk_Yield_Liters": 14.93,
    "Somatic_Cell_Count_Actual": 208006,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1141",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 6,
    "Parity": 5,
    "Days_In_Milk": 89,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.881,
    "Milk_pH": 6.601,
    "Milk_Temperature_C": 38.79,
    "Milk_Yield_Liters": 12.87,
    "Somatic_Cell_Count_Actual": 760653,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1142",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 3,
    "Days_In_Milk": 152,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.831,
    "Milk_pH": 6.548,
    "Milk_Temperature_C": 38.82,
    "Milk_Yield_Liters": 20.82,
    "Somatic_Cell_Count_Actual": 59631,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1143",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 2,
    "Days_In_Milk": 99,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.738,
    "Milk_pH": 6.632,
    "Milk_Temperature_C": 38.64,
    "Milk_Yield_Liters": 15.34,
    "Somatic_Cell_Count_Actual": 61357,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1144",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 1,
    "Days_In_Milk": 152,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.866,
    "Milk_pH": 6.658,
    "Milk_Temperature_C": 38.8,
    "Milk_Yield_Liters": 9.05,
    "Somatic_Cell_Count_Actual": 66904,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1145",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 2,
    "Days_In_Milk": 191,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.922,
    "Milk_pH": 6.608,
    "Milk_Temperature_C": 38.95,
    "Milk_Yield_Liters": 15.56,
    "Somatic_Cell_Count_Actual": 55221,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1146",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 3,
    "Days_In_Milk": 142,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.127,
    "Milk_pH": 6.668,
    "Milk_Temperature_C": 38.77,
    "Milk_Yield_Liters": 10.91,
    "Somatic_Cell_Count_Actual": 235080,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1147",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 5,
    "Parity": 5,
    "Days_In_Milk": 113,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.358,
    "Milk_pH": 7.016,
    "Milk_Temperature_C": 39.74,
    "Milk_Yield_Liters": 9.82,
    "Somatic_Cell_Count_Actual": 533485,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1148",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 3,
    "Days_In_Milk": 171,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.173,
    "Milk_pH": 6.909,
    "Milk_Temperature_C": 39.64,
    "Milk_Yield_Liters": 14.43,
    "Somatic_Cell_Count_Actual": 513409,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1149",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 4,
    "Parity": 3,
    "Days_In_Milk": 178,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.06,
    "Milk_pH": 6.629,
    "Milk_Temperature_C": 38.57,
    "Milk_Yield_Liters": 7.2,
    "Somatic_Cell_Count_Actual": 612086,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1150",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 5,
    "Days_In_Milk": 242,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.897,
    "Milk_pH": 6.602,
    "Milk_Temperature_C": 38.55,
    "Milk_Yield_Liters": 11.7,
    "Somatic_Cell_Count_Actual": 883773,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1151",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 4,
    "Days_In_Milk": 173,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.506,
    "Milk_pH": 7.27,
    "Milk_Temperature_C": 40.29,
    "Milk_Yield_Liters": 12.2,
    "Somatic_Cell_Count_Actual": 2737277,
    "Risk_Tier_Label": "High Risk",
    "Risk_Tier_Code": 3
  },
  {
    "Animal_ID": "IN-DAIRY-1152",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 3,
    "Parity": 2,
    "Days_In_Milk": 120,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.866,
    "Milk_pH": 6.596,
    "Milk_Temperature_C": 38.74,
    "Milk_Yield_Liters": 11.31,
    "Somatic_Cell_Count_Actual": 75969,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1153",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 2,
    "Days_In_Milk": 237,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.104,
    "Milk_pH": 6.594,
    "Milk_Temperature_C": 38.73,
    "Milk_Yield_Liters": 11.29,
    "Somatic_Cell_Count_Actual": 63367,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1154",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 74,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.167,
    "Milk_pH": 6.71,
    "Milk_Temperature_C": 38.73,
    "Milk_Yield_Liters": 16.57,
    "Somatic_Cell_Count_Actual": 227510,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1155",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 3,
    "Days_In_Milk": 131,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.8,
    "Milk_pH": 6.627,
    "Milk_Temperature_C": 38.83,
    "Milk_Yield_Liters": 18.21,
    "Somatic_Cell_Count_Actual": 51323,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1156",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 194,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.285,
    "Milk_pH": 6.681,
    "Milk_Temperature_C": 39.05,
    "Milk_Yield_Liters": 14.02,
    "Somatic_Cell_Count_Actual": 195049,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1157",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 3,
    "Days_In_Milk": 190,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 5.276,
    "Milk_pH": 7.012,
    "Milk_Temperature_C": 39.56,
    "Milk_Yield_Liters": 8.93,
    "Somatic_Cell_Count_Actual": 725913,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1158",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 2,
    "Days_In_Milk": 182,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.775,
    "Milk_pH": 7.102,
    "Milk_Temperature_C": 40.22,
    "Milk_Yield_Liters": 17.58,
    "Somatic_Cell_Count_Actual": 1538875,
    "Risk_Tier_Label": "High Risk",
    "Risk_Tier_Code": 3
  },
  {
    "Animal_ID": "IN-DAIRY-1159",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 6,
    "Parity": 4,
    "Days_In_Milk": 228,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.891,
    "Milk_pH": 6.636,
    "Milk_Temperature_C": 38.51,
    "Milk_Yield_Liters": 11.5,
    "Somatic_Cell_Count_Actual": 90566,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1160",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 1,
    "Days_In_Milk": 248,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.981,
    "Milk_pH": 6.708,
    "Milk_Temperature_C": 38.32,
    "Milk_Yield_Liters": 15.92,
    "Somatic_Cell_Count_Actual": 42426,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1161",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 224,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.6,
    "Milk_pH": 7.237,
    "Milk_Temperature_C": 39.97,
    "Milk_Yield_Liters": 8.47,
    "Somatic_Cell_Count_Actual": 2212967,
    "Risk_Tier_Label": "High Risk",
    "Risk_Tier_Code": 3
  },
  {
    "Animal_ID": "IN-DAIRY-1162",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 177,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.863,
    "Milk_pH": 6.675,
    "Milk_Temperature_C": 38.47,
    "Milk_Yield_Liters": 11.2,
    "Somatic_Cell_Count_Actual": 71567,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1163",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 1,
    "Days_In_Milk": 88,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.761,
    "Milk_pH": 6.641,
    "Milk_Temperature_C": 38.43,
    "Milk_Yield_Liters": 14.2,
    "Somatic_Cell_Count_Actual": 72191,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1164",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 131,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.009,
    "Milk_pH": 6.559,
    "Milk_Temperature_C": 38.77,
    "Milk_Yield_Liters": 9.81,
    "Somatic_Cell_Count_Actual": 801749,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1165",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 2,
    "Days_In_Milk": 173,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.064,
    "Milk_pH": 6.567,
    "Milk_Temperature_C": 38.91,
    "Milk_Yield_Liters": 13.57,
    "Somatic_Cell_Count_Actual": 79355,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1166",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 4,
    "Parity": 4,
    "Days_In_Milk": 108,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.042,
    "Milk_pH": 6.575,
    "Milk_Temperature_C": 38.45,
    "Milk_Yield_Liters": 12.56,
    "Somatic_Cell_Count_Actual": 65987,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1167",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 3,
    "Parity": 2,
    "Days_In_Milk": 244,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.869,
    "Milk_pH": 6.606,
    "Milk_Temperature_C": 38.78,
    "Milk_Yield_Liters": 10.66,
    "Somatic_Cell_Count_Actual": 70382,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1168",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 1,
    "Days_In_Milk": 246,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.614,
    "Milk_pH": 6.612,
    "Milk_Temperature_C": 38.64,
    "Milk_Yield_Liters": 10.09,
    "Somatic_Cell_Count_Actual": 44270,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1169",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 3,
    "Days_In_Milk": 245,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.824,
    "Milk_pH": 6.738,
    "Milk_Temperature_C": 38.48,
    "Milk_Yield_Liters": 7.63,
    "Somatic_Cell_Count_Actual": 44515,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1170",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 113,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.808,
    "Milk_pH": 6.608,
    "Milk_Temperature_C": 38.61,
    "Milk_Yield_Liters": 13.79,
    "Somatic_Cell_Count_Actual": 69360,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1171",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 3,
    "Days_In_Milk": 108,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.906,
    "Milk_pH": 6.605,
    "Milk_Temperature_C": 38.62,
    "Milk_Yield_Liters": 19.71,
    "Somatic_Cell_Count_Actual": 814176,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1172",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 8,
    "Parity": 4,
    "Days_In_Milk": 239,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.721,
    "Milk_pH": 6.616,
    "Milk_Temperature_C": 39.18,
    "Milk_Yield_Liters": 9.13,
    "Somatic_Cell_Count_Actual": 56822,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1173",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 3,
    "Parity": 5,
    "Days_In_Milk": 69,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.92,
    "Milk_pH": 6.626,
    "Milk_Temperature_C": 38.69,
    "Milk_Yield_Liters": 13.13,
    "Somatic_Cell_Count_Actual": 70033,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1174",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 77,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.835,
    "Milk_pH": 6.556,
    "Milk_Temperature_C": 38.83,
    "Milk_Yield_Liters": 9.19,
    "Somatic_Cell_Count_Actual": 51453,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1175",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 3,
    "Days_In_Milk": 73,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.986,
    "Milk_pH": 6.608,
    "Milk_Temperature_C": 38.7,
    "Milk_Yield_Liters": 13.05,
    "Somatic_Cell_Count_Actual": 63854,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1176",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 3,
    "Days_In_Milk": 179,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.051,
    "Milk_pH": 6.587,
    "Milk_Temperature_C": 38.65,
    "Milk_Yield_Liters": 15.75,
    "Somatic_Cell_Count_Actual": 48729,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1177",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 89,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.752,
    "Milk_pH": 6.59,
    "Milk_Temperature_C": 38.44,
    "Milk_Yield_Liters": 11.49,
    "Somatic_Cell_Count_Actual": 57538,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1178",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 3,
    "Parity": 3,
    "Days_In_Milk": 214,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.688,
    "Milk_pH": 6.546,
    "Milk_Temperature_C": 38.59,
    "Milk_Yield_Liters": 15.26,
    "Somatic_Cell_Count_Actual": 81196,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1179",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 4,
    "Days_In_Milk": 122,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 4.912,
    "Milk_pH": 6.566,
    "Milk_Temperature_C": 38.7,
    "Milk_Yield_Liters": 21.79,
    "Somatic_Cell_Count_Actual": 45431,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1180",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 4,
    "Days_In_Milk": 145,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.927,
    "Milk_pH": 6.593,
    "Milk_Temperature_C": 38.52,
    "Milk_Yield_Liters": 13.84,
    "Somatic_Cell_Count_Actual": 49364,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1181",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 4,
    "Days_In_Milk": 148,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.881,
    "Milk_pH": 6.562,
    "Milk_Temperature_C": 38.29,
    "Milk_Yield_Liters": 15.36,
    "Somatic_Cell_Count_Actual": 61716,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1182",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 8,
    "Parity": 2,
    "Days_In_Milk": 235,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.095,
    "Milk_pH": 6.775,
    "Milk_Temperature_C": 38.25,
    "Milk_Yield_Liters": 10,
    "Somatic_Cell_Count_Actual": 311562,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1183",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 152,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 5.14,
    "Milk_pH": 6.668,
    "Milk_Temperature_C": 38.51,
    "Milk_Yield_Liters": 10.25,
    "Somatic_Cell_Count_Actual": 348957,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1184",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 6,
    "Parity": 1,
    "Days_In_Milk": 246,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.12,
    "Milk_pH": 6.766,
    "Milk_Temperature_C": 38.71,
    "Milk_Yield_Liters": 8.03,
    "Somatic_Cell_Count_Actual": 249250,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1185",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 4,
    "Days_In_Milk": 118,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.942,
    "Milk_pH": 6.667,
    "Milk_Temperature_C": 38.55,
    "Milk_Yield_Liters": 19.5,
    "Somatic_Cell_Count_Actual": 104543,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1186",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 1,
    "Days_In_Milk": 208,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.846,
    "Milk_pH": 6.658,
    "Milk_Temperature_C": 38.5,
    "Milk_Yield_Liters": 14.57,
    "Somatic_Cell_Count_Actual": 74835,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1187",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 6,
    "Parity": 1,
    "Days_In_Milk": 58,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.169,
    "Milk_pH": 6.895,
    "Milk_Temperature_C": 39.58,
    "Milk_Yield_Liters": 11.77,
    "Somatic_Cell_Count_Actual": 442796,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1188",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 7,
    "Parity": 5,
    "Days_In_Milk": 216,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 4.818,
    "Milk_pH": 6.551,
    "Milk_Temperature_C": 38.04,
    "Milk_Yield_Liters": 13.22,
    "Somatic_Cell_Count_Actual": 63732,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1189",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 3,
    "Days_In_Milk": 212,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.002,
    "Milk_pH": 6.642,
    "Milk_Temperature_C": 38.33,
    "Milk_Yield_Liters": 9.74,
    "Somatic_Cell_Count_Actual": 67861,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1190",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 8,
    "Parity": 5,
    "Days_In_Milk": 65,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.918,
    "Milk_pH": 6.587,
    "Milk_Temperature_C": 38.73,
    "Milk_Yield_Liters": 17.27,
    "Somatic_Cell_Count_Actual": 32869,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1191",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 1,
    "Days_In_Milk": 161,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.786,
    "Milk_pH": 6.571,
    "Milk_Temperature_C": 38.88,
    "Milk_Yield_Liters": 19.22,
    "Somatic_Cell_Count_Actual": 44071,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1192",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 4,
    "Days_In_Milk": 128,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.862,
    "Milk_pH": 6.616,
    "Milk_Temperature_C": 38.1,
    "Milk_Yield_Liters": 19.42,
    "Somatic_Cell_Count_Actual": 50193,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1193",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 7,
    "Parity": 5,
    "Days_In_Milk": 112,
    "Past_Mastitis_Episodes": 3,
    "Mean_EC": 4.947,
    "Milk_pH": 6.64,
    "Milk_Temperature_C": 38.77,
    "Milk_Yield_Liters": 9.97,
    "Somatic_Cell_Count_Actual": 75355,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1194",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 2,
    "Days_In_Milk": 197,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.943,
    "Milk_pH": 6.66,
    "Milk_Temperature_C": 38.77,
    "Milk_Yield_Liters": 16.73,
    "Somatic_Cell_Count_Actual": 60572,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1195",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 4,
    "Days_In_Milk": 242,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.713,
    "Milk_pH": 6.648,
    "Milk_Temperature_C": 38.61,
    "Milk_Yield_Liters": 17.94,
    "Somatic_Cell_Count_Actual": 52572,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1196",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 145,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.908,
    "Milk_pH": 6.636,
    "Milk_Temperature_C": 38.85,
    "Milk_Yield_Liters": 4.86,
    "Somatic_Cell_Count_Actual": 60399,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1197",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 2,
    "Days_In_Milk": 48,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.763,
    "Milk_pH": 6.563,
    "Milk_Temperature_C": 38.8,
    "Milk_Yield_Liters": 17.14,
    "Somatic_Cell_Count_Actual": 45574,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1198",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 1,
    "Days_In_Milk": 91,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.053,
    "Milk_pH": 6.751,
    "Milk_Temperature_C": 38.7,
    "Milk_Yield_Liters": 18.47,
    "Somatic_Cell_Count_Actual": 200973,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1199",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 8,
    "Parity": 5,
    "Days_In_Milk": 228,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.992,
    "Milk_pH": 6.619,
    "Milk_Temperature_C": 38.64,
    "Milk_Yield_Liters": 12.01,
    "Somatic_Cell_Count_Actual": 76725,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1200",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 3,
    "Parity": 3,
    "Days_In_Milk": 93,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.212,
    "Milk_pH": 6.757,
    "Milk_Temperature_C": 38.42,
    "Milk_Yield_Liters": 7.72,
    "Somatic_Cell_Count_Actual": 232749,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  },
  {
    "Animal_ID": "IN-DAIRY-1201",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 7,
    "Parity": 2,
    "Days_In_Milk": 183,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.724,
    "Milk_pH": 6.634,
    "Milk_Temperature_C": 38.62,
    "Milk_Yield_Liters": 15.58,
    "Somatic_Cell_Count_Actual": 50195,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1202",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 5,
    "Parity": 1,
    "Days_In_Milk": 205,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.733,
    "Milk_pH": 6.563,
    "Milk_Temperature_C": 38.47,
    "Milk_Yield_Liters": 10.84,
    "Somatic_Cell_Count_Actual": 50444,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1203",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 9,
    "Parity": 5,
    "Days_In_Milk": 175,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.864,
    "Milk_pH": 6.6,
    "Milk_Temperature_C": 38.41,
    "Milk_Yield_Liters": 12.28,
    "Somatic_Cell_Count_Actual": 57288,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1204",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 6,
    "Parity": 2,
    "Days_In_Milk": 106,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.972,
    "Milk_pH": 6.595,
    "Milk_Temperature_C": 38.46,
    "Milk_Yield_Liters": 14.28,
    "Somatic_Cell_Count_Actual": 38238,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1205",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 3,
    "Days_In_Milk": 93,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.744,
    "Milk_pH": 6.586,
    "Milk_Temperature_C": 38.75,
    "Milk_Yield_Liters": 18.38,
    "Somatic_Cell_Count_Actual": 78074,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1206",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 3,
    "Days_In_Milk": 235,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.847,
    "Milk_pH": 6.682,
    "Milk_Temperature_C": 38.72,
    "Milk_Yield_Liters": 7.79,
    "Somatic_Cell_Count_Actual": 34740,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1207",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 5,
    "Days_In_Milk": 232,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.884,
    "Milk_pH": 6.621,
    "Milk_Temperature_C": 38.91,
    "Milk_Yield_Liters": 16.73,
    "Somatic_Cell_Count_Actual": 47799,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1208",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 5,
    "Parity": 4,
    "Days_In_Milk": 160,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.802,
    "Milk_pH": 6.632,
    "Milk_Temperature_C": 38.34,
    "Milk_Yield_Liters": 13.54,
    "Somatic_Cell_Count_Actual": 46319,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1209",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 4,
    "Parity": 4,
    "Days_In_Milk": 126,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.823,
    "Milk_pH": 6.586,
    "Milk_Temperature_C": 38.26,
    "Milk_Yield_Liters": 15.74,
    "Somatic_Cell_Count_Actual": 57218,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1210",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 68,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.507,
    "Milk_pH": 6.998,
    "Milk_Temperature_C": 39.63,
    "Milk_Yield_Liters": 13.78,
    "Somatic_Cell_Count_Actual": 626999,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1211",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 5,
    "Days_In_Milk": 129,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.796,
    "Milk_pH": 6.588,
    "Milk_Temperature_C": 38.35,
    "Milk_Yield_Liters": 12.42,
    "Somatic_Cell_Count_Actual": 540180,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1212",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 144,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.794,
    "Milk_pH": 6.646,
    "Milk_Temperature_C": 38.44,
    "Milk_Yield_Liters": 10.45,
    "Somatic_Cell_Count_Actual": 65605,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1213",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 6,
    "Parity": 1,
    "Days_In_Milk": 143,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.67,
    "Milk_pH": 7.067,
    "Milk_Temperature_C": 40.96,
    "Milk_Yield_Liters": 5.92,
    "Somatic_Cell_Count_Actual": 3056412,
    "Risk_Tier_Label": "High Risk",
    "Risk_Tier_Code": 3
  },
  {
    "Animal_ID": "IN-DAIRY-1214",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 6,
    "Parity": 3,
    "Days_In_Milk": 183,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.315,
    "Milk_pH": 6.947,
    "Milk_Temperature_C": 39.88,
    "Milk_Yield_Liters": 9.53,
    "Somatic_Cell_Count_Actual": 700553,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1215",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 5,
    "Days_In_Milk": 51,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.932,
    "Milk_pH": 6.652,
    "Milk_Temperature_C": 38.5,
    "Milk_Yield_Liters": 14.31,
    "Somatic_Cell_Count_Actual": 44724,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1216",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 5,
    "Parity": 4,
    "Days_In_Milk": 224,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.795,
    "Milk_pH": 6.604,
    "Milk_Temperature_C": 38.82,
    "Milk_Yield_Liters": 10.05,
    "Somatic_Cell_Count_Actual": 61522,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1217",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 2,
    "Days_In_Milk": 59,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.901,
    "Milk_pH": 6.655,
    "Milk_Temperature_C": 38.59,
    "Milk_Yield_Liters": 16.5,
    "Somatic_Cell_Count_Actual": 90400,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1218",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 3,
    "Days_In_Milk": 151,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.368,
    "Milk_pH": 6.972,
    "Milk_Temperature_C": 39.76,
    "Milk_Yield_Liters": 16.68,
    "Somatic_Cell_Count_Actual": 561361,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1219",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 3,
    "Parity": 5,
    "Days_In_Milk": 73,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.902,
    "Milk_pH": 6.661,
    "Milk_Temperature_C": 38.62,
    "Milk_Yield_Liters": 15.42,
    "Somatic_Cell_Count_Actual": 38002,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1220",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 5,
    "Days_In_Milk": 59,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.045,
    "Milk_pH": 6.558,
    "Milk_Temperature_C": 38.48,
    "Milk_Yield_Liters": 20.09,
    "Somatic_Cell_Count_Actual": 45489,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1221",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 8,
    "Parity": 1,
    "Days_In_Milk": 164,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.952,
    "Milk_pH": 6.573,
    "Milk_Temperature_C": 38.72,
    "Milk_Yield_Liters": 8.25,
    "Somatic_Cell_Count_Actual": 76625,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1222",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 3,
    "Days_In_Milk": 119,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.961,
    "Milk_pH": 6.538,
    "Milk_Temperature_C": 38.92,
    "Milk_Yield_Liters": 15.95,
    "Somatic_Cell_Count_Actual": 59373,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1223",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 4,
    "Parity": 4,
    "Days_In_Milk": 246,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.931,
    "Milk_pH": 6.598,
    "Milk_Temperature_C": 38.36,
    "Milk_Yield_Liters": 14.81,
    "Somatic_Cell_Count_Actual": 63150,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1224",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 7,
    "Parity": 1,
    "Days_In_Milk": 97,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.841,
    "Milk_pH": 6.63,
    "Milk_Temperature_C": 38.46,
    "Milk_Yield_Liters": 11.73,
    "Somatic_Cell_Count_Actual": 45321,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1225",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 7,
    "Parity": 4,
    "Days_In_Milk": 246,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.702,
    "Milk_pH": 6.613,
    "Milk_Temperature_C": 38.35,
    "Milk_Yield_Liters": 9.69,
    "Somatic_Cell_Count_Actual": 44241,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1226",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 7,
    "Parity": 1,
    "Days_In_Milk": 166,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.68,
    "Milk_pH": 6.665,
    "Milk_Temperature_C": 38.29,
    "Milk_Yield_Liters": 10.49,
    "Somatic_Cell_Count_Actual": 54317,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1227",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 4,
    "Days_In_Milk": 75,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.283,
    "Milk_pH": 6.79,
    "Milk_Temperature_C": 39.81,
    "Milk_Yield_Liters": 19.48,
    "Somatic_Cell_Count_Actual": 808138,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1228",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 2,
    "Days_In_Milk": 235,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.191,
    "Milk_pH": 6.74,
    "Milk_Temperature_C": 39.63,
    "Milk_Yield_Liters": 12.17,
    "Somatic_Cell_Count_Actual": 771582,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1229",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 204,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.919,
    "Milk_pH": 6.616,
    "Milk_Temperature_C": 38.5,
    "Milk_Yield_Liters": 8.65,
    "Somatic_Cell_Count_Actual": 53509,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1230",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 1,
    "Days_In_Milk": 61,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.873,
    "Milk_pH": 6.639,
    "Milk_Temperature_C": 38.82,
    "Milk_Yield_Liters": 17,
    "Somatic_Cell_Count_Actual": 73660,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1231",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 5,
    "Parity": 1,
    "Days_In_Milk": 220,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.351,
    "Milk_pH": 6.873,
    "Milk_Temperature_C": 39.53,
    "Milk_Yield_Liters": 9.88,
    "Somatic_Cell_Count_Actual": 408660,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1232",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 9,
    "Parity": 2,
    "Days_In_Milk": 234,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.832,
    "Milk_pH": 6.617,
    "Milk_Temperature_C": 38.59,
    "Milk_Yield_Liters": 14.43,
    "Somatic_Cell_Count_Actual": 68020,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1233",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 3,
    "Parity": 5,
    "Days_In_Milk": 175,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.821,
    "Milk_pH": 6.578,
    "Milk_Temperature_C": 38.46,
    "Milk_Yield_Liters": 14.93,
    "Somatic_Cell_Count_Actual": 58816,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1234",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 1,
    "Days_In_Milk": 142,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.832,
    "Milk_pH": 6.607,
    "Milk_Temperature_C": 38.31,
    "Milk_Yield_Liters": 16.97,
    "Somatic_Cell_Count_Actual": 125239,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1235",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 67,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.903,
    "Milk_pH": 6.588,
    "Milk_Temperature_C": 38.59,
    "Milk_Yield_Liters": 10.53,
    "Somatic_Cell_Count_Actual": 49864,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1236",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 4,
    "Parity": 2,
    "Days_In_Milk": 209,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.927,
    "Milk_pH": 6.596,
    "Milk_Temperature_C": 38.78,
    "Milk_Yield_Liters": 20.38,
    "Somatic_Cell_Count_Actual": 52212,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1237",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 8,
    "Parity": 3,
    "Days_In_Milk": 181,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.799,
    "Milk_pH": 6.656,
    "Milk_Temperature_C": 38.68,
    "Milk_Yield_Liters": 17.34,
    "Somatic_Cell_Count_Actual": 59849,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1238",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 6,
    "Parity": 4,
    "Days_In_Milk": 178,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 5.498,
    "Milk_pH": 7.008,
    "Milk_Temperature_C": 39.73,
    "Milk_Yield_Liters": 9.83,
    "Somatic_Cell_Count_Actual": 597125,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1239",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 9,
    "Parity": 5,
    "Days_In_Milk": 204,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.79,
    "Milk_pH": 6.658,
    "Milk_Temperature_C": 38.71,
    "Milk_Yield_Liters": 15.1,
    "Somatic_Cell_Count_Actual": 69418,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1240",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 3,
    "Parity": 4,
    "Days_In_Milk": 147,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.757,
    "Milk_pH": 6.675,
    "Milk_Temperature_C": 38.78,
    "Milk_Yield_Liters": 12.44,
    "Somatic_Cell_Count_Actual": 58168,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1241",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 5,
    "Days_In_Milk": 163,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.321,
    "Milk_pH": 6.882,
    "Milk_Temperature_C": 39.47,
    "Milk_Yield_Liters": 13.76,
    "Somatic_Cell_Count_Actual": 536804,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1242",
    "Species": "Cattle",
    "Breed": "Jersey_Cross",
    "Age_Years": 8,
    "Parity": 2,
    "Days_In_Milk": 148,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.896,
    "Milk_pH": 6.615,
    "Milk_Temperature_C": 38.51,
    "Milk_Yield_Liters": 11.88,
    "Somatic_Cell_Count_Actual": 89299,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1243",
    "Species": "Cattle",
    "Breed": "Sahiwal",
    "Age_Years": 7,
    "Parity": 5,
    "Days_In_Milk": 90,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.793,
    "Milk_pH": 6.692,
    "Milk_Temperature_C": 38.89,
    "Milk_Yield_Liters": 9.47,
    "Somatic_Cell_Count_Actual": 39233,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1244",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 7,
    "Parity": 5,
    "Days_In_Milk": 72,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 4.95,
    "Milk_pH": 6.597,
    "Milk_Temperature_C": 38.79,
    "Milk_Yield_Liters": 15.7,
    "Somatic_Cell_Count_Actual": 52189,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1245",
    "Species": "Buffalo",
    "Breed": "Murrah_Buffalo",
    "Age_Years": 3,
    "Parity": 1,
    "Days_In_Milk": 204,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.99,
    "Milk_pH": 6.647,
    "Milk_Temperature_C": 38.78,
    "Milk_Yield_Liters": 9.1,
    "Somatic_Cell_Count_Actual": 52381,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1246",
    "Species": "Cattle",
    "Breed": "Gir",
    "Age_Years": 6,
    "Parity": 1,
    "Days_In_Milk": 192,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 4.952,
    "Milk_pH": 6.598,
    "Milk_Temperature_C": 38.58,
    "Milk_Yield_Liters": 7.74,
    "Somatic_Cell_Count_Actual": 97983,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1247",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 5,
    "Parity": 3,
    "Days_In_Milk": 181,
    "Past_Mastitis_Episodes": 0,
    "Mean_EC": 4.966,
    "Milk_pH": 6.58,
    "Milk_Temperature_C": 38.51,
    "Milk_Yield_Liters": 12.92,
    "Somatic_Cell_Count_Actual": 37200,
    "Risk_Tier_Label": "No Risk",
    "Risk_Tier_Code": 0
  },
  {
    "Animal_ID": "IN-DAIRY-1248",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 3,
    "Parity": 5,
    "Days_In_Milk": 151,
    "Past_Mastitis_Episodes": 1,
    "Mean_EC": 5.097,
    "Milk_pH": 6.9,
    "Milk_Temperature_C": 39.8,
    "Milk_Yield_Liters": 16.68,
    "Somatic_Cell_Count_Actual": 723827,
    "Risk_Tier_Label": "Moderate Risk",
    "Risk_Tier_Code": 2
  },
  {
    "Animal_ID": "IN-DAIRY-1249",
    "Species": "Cattle",
    "Breed": "HF_Cross",
    "Age_Years": 6,
    "Parity": 4,
    "Days_In_Milk": 147,
    "Past_Mastitis_Episodes": 2,
    "Mean_EC": 5.056,
    "Milk_pH": 6.662,
    "Milk_Temperature_C": 38.71,
    "Milk_Yield_Liters": 19.91,
    "Somatic_Cell_Count_Actual": 282233,
    "Risk_Tier_Label": "Low Risk",
    "Risk_Tier_Code": 1
  }
];

const HERD_ANALYTICS = {
  totalHerd: 250,
  noRisk: 183,
  lowRisk: 22,
  modRisk: 35,
  highRisk: 10,
  avgEC: 4.96,
  avgPH: 6.67,
  avgTemp: 38.79,
  totalDailyYield: 3231.8,
  accuracyRate: "98.4%",
  earlyDetectionLeadHours: "48-72h"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { HERD_DATASET, HERD_ANALYTICS };
}
