// ================================================================
// MooTracker ML Thresholds for ESP32
// Auto-generated by train_and_export.py
// Model : GradientBoostingClassifier
// ROC-AUC           : 0.9926
// Dataset rows      : 1500
// Decision threshold: 0.40
// ================================================================

#ifndef MOOTRACKER_ML_H
#define MOOTRACKER_ML_H

// ── MILK CONDUCTIVITY (mS/cm) ─────────────────────────────────────
// Normal range  : 4.334 - 6.07
// High-risk mean: 6.305
#define EC_NORMAL_MIN    4.334f
#define EC_NORMAL_MAX    6.07f
#define EC_HIGHRISK_MEAN 6.305f
#define EC_ALERT_HIGH    5.962f   // above this = elevated risk

// ── MILK TEMPERATURE (deg C) ──────────────────────────────────────
// Normal range  : 36.584 - 37.586
// High-risk mean: 37.544
#define MILK_TEMP_NORMAL_MIN 36.584f
#define MILK_TEMP_NORMAL_MAX 37.586f
#define MILK_TEMP_ALERT      37.531f

// ── MILK pH ───────────────────────────────────────────────────────
// Normal range  : 6.53 - 6.81
// High-risk mean: 6.776
#define PH_NORMAL_MIN  6.53f
#define PH_NORMAL_MAX  6.81f
#define PH_ALERT_HIGH  6.8f   // above = alkaline shift

// ── SOMATIC CELL COUNT (cells/mL) ─────────────────────────────────
// Normal range  : 95 - 322
// High-risk mean: 285
#define SCC_NORMAL_MIN    95
#define SCC_NORMAL_MAX    322
#define SCC_HIGHRISK_MEAN 285
#define SCC_ALERT_HIGH    304   // above = subclinical mastitis likely

// ── BODY TEMPERATURE (deg C) ──────────────────────────────────────
// Normal range  : 38.11 - 38.77
// High-risk mean: 38.829
#define BODY_TEMP_NORMAL_MIN 38.11f
#define BODY_TEMP_NORMAL_MAX 38.77f
#define BODY_TEMP_ALERT      38.754f

// ── ACTIVITY SCORE (0-100) ────────────────────────────────────────
// Normal range  : 53.135 - 92.8
// High-risk mean: 66.619
#define ACTIVITY_NORMAL_MIN 53.135f
#define ACTIVITY_NORMAL_MAX 92.8f
#define ACTIVITY_ALERT_LOW  52.186f   // below = reduced activity = risk

// ── RUMINATION (minutes/day) ──────────────────────────────────────
// Normal range  : 312.835 - 500.59
#define RUMINATION_NORMAL_MIN 312.835f
#define RUMINATION_NORMAL_MAX 500.59f
#define RUMINATION_ALERT_LOW  316.295f

// ── FEEDING TIME (minutes/day) ────────────────────────────────────
// Normal range  : 132.135 - 165.965
#define FEEDING_NORMAL_MIN 132.135f
#define FEEDING_NORMAL_MAX 165.965f
#define FEEDING_ALERT_LOW  132.416f

// ── MILK YIELD (litres/session) ───────────────────────────────────
// Normal range  : 8.171 - 19.41
// High-risk mean: 12.236
#define YIELD_NORMAL_MIN 8.171f
#define YIELD_NORMAL_MAX 19.41f
#define YIELD_ALERT_LOW  8.472f   // below = yield drop = risk

// ── ML FEATURE WEIGHTS (from GBT feature_importances_) ───────────
// Use these to compute a weighted risk score on the ESP32
#define WEIGHT_EC          0.12f
#define WEIGHT_MILK_TEMP   0.09f
#define WEIGHT_PH          0.08f
#define WEIGHT_SCC         0.13f
#define WEIGHT_BODY_TEMP   0.11f
#define WEIGHT_ACTIVITY    0.10f
#define WEIGHT_RUMINATION  0.12f
#define WEIGHT_FEEDING     0.10f
#define WEIGHT_YIELD       0.15f

// ── RISK BAND THRESHOLDS ─────────────────────────────────────────
#define RISK_SCORE_LOW       25.0f   //  0-25: LOW   (green LED)
#define RISK_SCORE_MODERATE  50.0f   // 25-50: WATCH (yellow LED)
#define RISK_SCORE_HIGH      75.0f   // 50-75: HIGH  (orange LED)
// Above 75: CRITICAL -> red LED + buzzer + WiFi alert

// ── computeRiskScore() TEMPLATE ──────────────────────────────────
//
// float computeRiskScore(float ec, float milkTemp, float ph,
//                        int   scc, float bodyTemp,
//                        float activity, float rumination,
//                        float feeding, float yield_L) {
//   float score = 0.0f;
//
//   if (ec > EC_ALERT_HIGH)
//     score += WEIGHT_EC * 100.0f *
//              constrain((ec - EC_NORMAL_MAX) / (EC_HIGHRISK_MEAN - EC_NORMAL_MAX), 0.0f, 1.0f);
//
//   if (scc > SCC_ALERT_HIGH)
//     score += WEIGHT_SCC * 100.0f *
//              constrain((float)(scc - SCC_NORMAL_MAX) / (SCC_HIGHRISK_MEAN - SCC_NORMAL_MAX), 0.0f, 1.0f);
//
//   if (bodyTemp > BODY_TEMP_ALERT)  score += WEIGHT_BODY_TEMP * 100.0f;
//   if (ph > PH_ALERT_HIGH)          score += WEIGHT_PH * 100.0f;
//   if (activity < ACTIVITY_ALERT_LOW) score += WEIGHT_ACTIVITY * 100.0f;
//   if (yield_L  < YIELD_ALERT_LOW)    score += WEIGHT_YIELD * 100.0f;
//
//   return constrain(score, 0.0f, 100.0f);
// }

#endif // MOOTRACKER_ML_H
